version: "3.8"

services:
  database:
    image: postgres:15.2-alpine3.17
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"

  server:
    build: ../../application/server
    container_name: server
    restart: unless-stopped
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: database
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - database
