name: Server

on:
  push:
    branches:
      - master
    paths:
      - 'application/server/**'
  pull_request:
    branches:
      - master
    paths:
      - 'application/server/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.6+10'
          cache: 'maven'

      - name: Build the project
        run: mvn --batch-mode --update-snapshots package -DskipTests
        working-directory: application/server
